name       : ruby-thor
version    : 1.2.2
release    : 10
source     :
    - https://rubygems.org/downloads/thor-1.2.2.gem : 2f93c652828cba9fcf4f65f5dc8c306f1a7317e05aad5835a13740122c17f24c
homepage   : https://rubygems.org/gems/thor
license    : MIT
component  : programming.ruby
summary    : Thor is a toolkit for building powerful command-line interfaces
description: |
    Thor is a toolkit for building powerful command-line interfaces.
builddeps  :
    - pkgconfig(ruby-3.2)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
