name       : ruby-thor
version    : 0.2
release    : 2
source     :
    - https://rubygems.org/downloads/thor-0.20.0.gem : b47dad86e151c08921cf935c1ad2be4d9982e435784d6bc223530b62a4bfb85a
license    : MIT
component  : programming.ruby
summary    : Thor is a toolkit for building powerful command-line interfaces.
description: |
    Thor is a toolkit for building powerful command-line interfaces.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby
install    : |
    %gem_install
