name       : ruby-thor
version    : 1.2.1
release    : 8
source     :
    - https://rubygems.org/downloads/thor-1.2.1.gem : b1752153dc9c6b8d3fcaa665e9e1a00a3e73f28da5e238b81c404502e539d446
homepage   : https://rubygems.org/gems/thor
license    : MIT
component  : programming.ruby
summary    : Thor is a toolkit for building powerful command-line interfaces
description: |
    Thor is a toolkit for building powerful command-line interfaces.
builddeps  :
    - pkgconfig(ruby-3.1)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
